config/routes.rb
FruitStand::Application.routes.draw do

  get "log_out", to: "sessions#destroy", as: "log_out"
  get "log_in", to: "sessions#new", as: "log_in"
  get "sign_up", to: "users#new", as: "sign_up"
  resources :users
  resources :sessions

  get "products", to: "products#index", as: "products"

  get '/cart', to: "cart#show", as: "show_cart"
  post '/cart/add_item', to: "cart#add_item", as: "add_item"
  post '/cart/remove_item/:id', to: "cart#remove_item", as: "remove_item"
  post '/cart/checkout', to: "cart#checkout", as: "checkout"

  #root to: 'users#new'
  root :to => 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  attr_accessible :total

  has_many :line_items, as: :itemable, dependent: :destroy

  #monetize :total_cents

  def total
    t = 0
    line_items.each do |line_item|
      t += line_item.total
    end
  t
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  attr_accessible :price, :product_id, :quantity

  belongs_to :cart
  belongs_to :product

  def total
    quantity * self.product.price
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  # attr_accessible :title, :body

  has_many :line_items, as: :itemable

  def bill
    true
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  attr_accessible :name, :price

  has_many :line_items

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: true

  #monetize :price_cents


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash  == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
   end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private
  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end


  def add_item
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
    @product = Product.find(params[:product_id])
    if @line_item = @cart.line_items.find_by_product_id(@product.id)
      @line_item.quantity += 1
    else
      @line_item = @cart.line_items.build(product_id: @product.id, quantity: 1, price: @product.price)
    end
    if @line_item.save
      flash[:notice] = "#{@product.name} added to cart"
    else
      flash[:error] = "#{@product.name} NOT added to cart"
    end
    redirect_to root_path
  end


  def remove_item
    @cart = Cart.find(session[:cart_id])
    @line_item = @cart.line_items.find(params[:id])
    if @line_item.destroy
      flash[:notice] = "#{@line_item.product.name} removed from cart"
    else
      flash[:error] = "#{@line_item.product.name} NOT removed from cart"
    end
    redirect_to show_cart_path
  end


  def checkout
    @cart = Cart.find(session[:cart_id])
    @order = Order.create
    @cart.line_items.each do |line_item|
      @order.line_items << LineItem.new({product_id: line_item.product_id, quantity: line_item.quantity, price: line_item.total})
    end

    if @order.save
      OrderMailer.order_notification(current_user).deliver
      session[:cart_id] = nil
      @cart.destroy
      flash[:notice] = "Thank you for your order"
      redirect_to root_path
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    @cart = Cart.find_or_create_by_id(session[:cart_id])
    session[:cart_id] ||= @cart.id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to products_path, :notice => "Logged In!"
    else
      flash.now.alert = "Invalid email address or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed Up"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def cents_to_dollars(number)
    sprintf('%.2f', number / 100.0)
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/show.html.erb
<table class='table'>
  <thead>
  <tr>
    <th>Product</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Total</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @cart.line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product.name %></td>
        <td>$<%= cents_to_dollars(line_item.price) %></td>
        <td><%= line_item.quantity %></td>
        <td>$<%= cents_to_dollars(line_item.total) %></td>
        <td><%= link_to "Remove Item", remove_item_path(line_item.id), :method => :post, confirm: "Are you sure?", class: 'btn btn-danger' %></td>
      </tr>
  <% end %>
  <tr>
    <td colspan='3' style='text-align: right'><strong>Cart Total is:</strong></td>
    <td> $<%= @cart.total %></td>
    <td>&nbsp;</td>
  </tr>
  </tbody>
</table>
<p><%= link_to "Checkout", checkout_path, :method => :post %></p>
<%= link_to "Continue Shopping", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= link_to "Log Out", log_out_path %>
  <% else %>
    <%= link_to "Sign Up", sign_up_path %> or
    <%= link_to "Log In", log_in_path %>
  <% end %>
</div>

<head>
  <title>FruitStand</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>
<table>
  <thead>
  <tr>
    <th>Price</th>
    <th>Product</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
<% @products.each do |product| %>
      <tr>
        <td>$<%= cents_to_dollars(product.price) %></td>
        <td><%= product.name %></td>
        <td><%= button_to "Add To Cart", :controller => "cart", :action => "add_item", :id => @cart.id, :product_id => product.id %></td>
      </tr>
 <% end %>
  </tbody>
</table>
<%= link_to "Cart has #{@cart.line_items.size} item(s)", show_cart_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>